// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, customerID int64) (Order, error)
	CreateOrderItems(ctx context.Context, arg CreateOrderItemsParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	FetchPrice(ctx context.Context, id int64) (int32, error)
	FindOrderById(ctx context.Context, id int64) ([]FindOrderByIdRow, error)
	FindProductsById(ctx context.Context, id int64) (Product, error)
	ListOrders(ctx context.Context) ([]Order, error)
	ListProducts(ctx context.Context) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
