// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, price_in_cents, quantity) VALUES ($1, $2, $3) RETURNING id, name, price_in_cents, quantity, created_at
`

type CreateProductParams struct {
	Name         string `json:"name"`
	PriceInCents int32  `json:"price_in_cents"`
	Quantity     int32  `json:"quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.PriceInCents, arg.Quantity)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const findOrderById = `-- name: FindOrderById :many
SELECT orders.id,
    orders.customer_id,
    orders.created_at,
    order_items.product_id,
    order_items.quantity,
    order_items.price_cents
FROM orders
    INNER JOIN order_items ON orders.id = order_items.order_id
WHERE orders.id = $1
`

type FindOrderByIdRow struct {
	ID         int64              `json:"id"`
	CustomerID int64              `json:"customer_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ProductID  int64              `json:"product_id"`
	Quantity   int32              `json:"quantity"`
	PriceCents int32              `json:"price_cents"`
}

func (q *Queries) FindOrderById(ctx context.Context, id int64) ([]FindOrderByIdRow, error) {
	rows, err := q.db.Query(ctx, findOrderById, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindOrderByIdRow
	for rows.Next() {
		var i FindOrderByIdRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.CreatedAt,
			&i.ProductID,
			&i.Quantity,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findProductsById = `-- name: FindProductsById :one
SELECT id, name, price_in_cents, quantity, created_at
FROM products
WHERE id = $1
`

func (q *Queries) FindProductsById(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, findProductsById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, customer_id, created_at
FROM orders
`

func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(&i.ID, &i.CustomerID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price_in_cents, quantity, created_at
FROM products
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCents,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
