// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	FindOrderById(ctx context.Context, id int64) ([]FindOrderByIdRow, error)
	FindProductsById(ctx context.Context, id int64) (Product, error)
	ListOrders(ctx context.Context) ([]Order, error)
	ListProducts(ctx context.Context) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
